### ISSUE TITLE
Class Df\Payment\Method not found

### ISSUE THREAD

**Issue by deepmalik11** [mage2pro/checkout.com#1]
Hi,

When i run command "php bin/magento setup:upgrade", it through an error "Php Fatal error : Class Df\Payment\Method not found in app/code/Dfe/CheckoutCom/Method.php line no. 22 "..

I download module from : https://github.com/mage2pro/checkout.com

Please let me know how i proceed..

Regards

**Comment by dmitrii-fediuk** [comment]
You should learn always read installation manuals before doing / reporting: https://github.com/mage2pro/checkout.com#how-to-install
It is not a rocket science at all.

**Comment by deepmalik11** [comment]
Yes i should learn read installation manuals.. 
Its working now...
Thanks
